export interface Club {
  id: string;
  name: string;
  rotaryId: string;
  memberCount: number;
  type: string;
  state: string;
  city?: string;
  region: string;
  meetingVenue: string;
  meetingDay?: string;
  meetingTime?: string;
  meetingSchedule?: string;
  president?: string;
  presidentAvatar?: string;
  presidentPhone?: string;
  instagramUrl?: string;
  coordinates: {
    lat: number;
    lng: number;
  };
}

export const clubsData: Club[] = [
  // SOUTH-WEST REGION — Oyo State (20 Clubs)
  {
    id: 'club-ibadan-ring-road',
    name: 'RAC Ibadan Ring Road',
    rotaryId: '218112',
    memberCount: 11,
    type: 'Community',
    state: 'Oyo',
    city: 'Ibadan',
    region: 'South-West',
    meetingVenue: 'Rotary Center, Iyaganku GRA, Ring Road, Ibadan',
    meetingSchedule: 'Every 1st & 3rd Sunday · 4:00 PM',
    president: 'Peleyeju Timileyin Omotayo',
    presidentAvatar: '/images/presidents/peleyeju-timileyin-omotayo.jpg',
    presidentPhone: '+234 902 115 5714',
    instagramUrl: 'https://www.instagram.com/racib.ringroad/',
    coordinates: { lat: 7.3775, lng: 3.8670 },
  },
  {
    id: 'club-ui-ibadan',
    name: 'RAC University of Ibadan',
    rotaryId: '50205',
    memberCount: 19,
    type: 'Campus',
    state: 'Oyo',
    city: 'Ibadan',
    region: 'South-West',
    meetingVenue: 'SRC Chamber, SUB (Physical) / Google Meet (Virtual)',
    meetingSchedule: 'Every Sunday · 3:30 PM for 4:00 PM',
    president: 'Samson Oluwatobiloba Sharon',
    presidentAvatar: '/images/presidents/samson-oluwatobiloba-sharon.jpg',
    presidentPhone: '+234 702 565 2468',
    coordinates: { lat: 7.4443, lng: 3.8997 },
  },
  {
    id: 'club-lead-city-univ',
    name: 'RAC Lead City University Ibadan',
    rotaryId: '217577',
    memberCount: 20,
    type: 'Campus',
    state: 'Oyo',
    city: 'Ibadan',
    region: 'South-West',
    meetingVenue: 'International Conference Hall, Lead City Campus, Ibadan',
    meetingSchedule: 'Every Thursday · 4:30 PM',
    president: 'Folashade Bello',
    coordinates: { lat: 7.3486, lng: 3.8828 },
  },
  {
    id: 'club-the-poly-ibadan',
    name: 'RAC The Polytechnic Ibadan',
    rotaryId: '8827452',
    memberCount: 10,
    type: 'Campus',
    state: 'Oyo',
    city: 'Ibadan',
    region: 'South-West',
    meetingVenue: 'North Campus Assembly Hall, The Poly Ibadan',
    meetingSchedule: 'Every Wednesday · 4:00 PM',
    president: 'Babatunde Alao',
    coordinates: { lat: 7.4326, lng: 3.8744 },
  },
  {
    id: 'club-uch-ibadan',
    name: 'RAC University College Hospital, Ibadan',
    rotaryId: '214344',
    memberCount: 12,
    type: 'Campus',
    state: 'Oyo',
    city: 'Ibadan',
    region: 'South-West',
    meetingVenue: 'Famewo Common Room (FCR) in ABH, UCH Ibadan',
    meetingSchedule: 'Every 2nd & 4th Sunday of the Month',
    president: 'Solarin Imisioluwa',
    presidentAvatar: '/images/presidents/solarin-imisioluwa.jpg',
    presidentPhone: '+234 810 571 8463',
    coordinates: { lat: 7.4022, lng: 3.9048 },
  },
  {
    id: 'club-fca-ibadan',
    name: 'RAC Federal College of Agriculture Moor Plantation Ibadan',
    rotaryId: '215293',
    memberCount: 8,
    type: 'Campus',
    state: 'Oyo',
    city: 'Ibadan',
    region: 'South-West',
    meetingVenue: 'Agriculture Tech, ND1 lecture room, FCAIB (Physical)',
    meetingSchedule: 'Every Wednesday · 4:00 PM',
    president: 'Adebusoye Opeyemi Favour',
    presidentAvatar: '/images/presidents/adebusoye-opeyemi-favour.jpg',
    coordinates: { lat: 7.3820, lng: 3.8490 },
  },
  {
    id: 'club-fcc-ibadan',
    name: 'RAC Federal Cooperative College Ibadan',
    rotaryId: '213611',
    memberCount: 3,
    type: 'Campus',
    state: 'Oyo',
    city: 'Ibadan',
    region: 'South-West',
    meetingVenue: 'Cooperative Lecture Theatre, FCC Campus, Ibadan',
    meetingSchedule: 'Every Wednesday · 4:30 PM',
    president: 'Damilola Ajayi',
    coordinates: { lat: 7.4110, lng: 3.8680 },
  },
  {
    id: 'club-fss-oyo',
    name: 'RAC Federal School of Surveying, Oyo',
    rotaryId: '91159',
    memberCount: 9,
    type: 'Campus',
    state: 'Oyo',
    city: 'Oyo Town',
    region: 'South-West',
    meetingVenue: 'School Main Auditorium, FSS Campus, Oyo Town',
    meetingSchedule: 'Every Thursday · 4:00 PM',
    president: 'Sikiru Oladipo',
    coordinates: { lat: 7.8500, lng: 3.9333 },
  },
  {
    id: 'club-tech-u-ibadan',
    name: 'RAC First Technical University Ibadan',
    rotaryId: '8824739',
    memberCount: 11,
    type: 'Campus',
    state: 'Oyo',
    city: 'Ibadan',
    region: 'South-West',
    meetingVenue: 'Senate Building Lawn, Tech-U Lagos-Ibadan Expressway',
    meetingSchedule: 'Every Friday · 4:00 PM',
    president: 'Ayomide Balogun',
    coordinates: { lat: 7.3020, lng: 3.9320 },
  },
  {
    id: 'club-ibadan-akobo',
    name: 'RAC Ibadan Akobo',
    rotaryId: '90002',
    memberCount: 8,
    type: 'Community',
    state: 'Oyo',
    city: 'Ibadan',
    region: 'South-West',
    meetingVenue: 'Akobo Community Center, Iwo Road Axis, Ibadan',
    meetingSchedule: 'Every 2nd & 4th Sunday · 4:30 PM',
    president: 'Kayode Alabi',
    coordinates: { lat: 7.4520, lng: 3.9310 },
  },
  {
    id: 'club-ibadan-ologuneru',
    name: 'RAC Ibadan Ologuneru',
    rotaryId: '8826945',
    memberCount: 12,
    type: 'Community',
    state: 'Oyo',
    city: 'Ibadan',
    region: 'South-West',
    meetingVenue: 'Ologuneru Town Hall, Eleyele Extension, Ibadan',
    meetingSchedule: 'Every 1st & 3rd Saturday · 4:00 PM',
    president: 'Omolara Adeleke',
    coordinates: { lat: 7.4120, lng: 3.8320 },
  },
  {
    id: 'club-ibadan-oritamefa',
    name: 'RAC Ibadan-Oritamefa',
    rotaryId: '215660',
    memberCount: 2,
    type: 'Community',
    state: 'Oyo',
    city: 'Ibadan',
    region: 'South-West',
    meetingVenue: 'Oritamefa Baptist Church Hall Area, Total Garden, Ibadan',
    meetingSchedule: 'Every 2nd & 4th Sunday · 4:00 PM',
    president: 'Segun Adekanmbi',
    coordinates: { lat: 7.3990, lng: 3.9020 },
  },
  {
    id: 'club-felele',
    name: 'RAC Felele',
    rotaryId: '215596',
    memberCount: 6,
    type: 'Community',
    state: 'Oyo',
    city: 'Ibadan',
    region: 'South-West',
    meetingVenue: 'Felele Layout Community Center, Challenge, Ibadan',
    meetingSchedule: 'Every 1st & 3rd Sunday · 4:00 PM',
    president: 'Adewale Osinubi',
    coordinates: { lat: 7.3510, lng: 3.8750 },
  },
  {
    id: 'club-moor-plantation',
    name: 'RAC Moor Plantation',
    rotaryId: '74374',
    memberCount: 3,
    type: 'Community',
    state: 'Oyo',
    city: 'Ibadan',
    region: 'South-West',
    meetingVenue: 'IAR&T Conference Center, Moor Plantation, Ibadan',
    meetingSchedule: 'Every 2nd & 4th Saturday · 3:30 PM',
    president: 'Titilayo Coker',
    coordinates: { lat: 7.3780, lng: 3.8510 },
  },
  {
    id: 'club-oyo-central',
    name: 'RAC Oyo Central',
    rotaryId: '216394',
    memberCount: 11,
    type: 'Community',
    state: 'Oyo',
    city: 'Oyo Town',
    region: 'South-West',
    meetingVenue: 'Oyo Royal Club Hall, Owode, Oyo Town',
    meetingSchedule: 'Every 1st & 3rd Sunday · 4:00 PM',
    president: 'Ganiyu Ojo',
    coordinates: { lat: 7.8420, lng: 3.9310 },
  },
  {
    id: 'club-iseyin-pathfinder',
    name: 'RAC Iseyin Pathfinder',
    rotaryId: '8824492',
    memberCount: 6,
    type: 'Community',
    state: 'Oyo',
    city: 'Iseyin',
    region: 'South-West',
    meetingVenue: 'Iseyin Civic Center, Oluwole Area, Iseyin',
    meetingSchedule: 'Every 2nd & 4th Saturday · 4:00 PM',
    president: 'Rasheed Arowolo',
    coordinates: { lat: 7.9660, lng: 3.5980 },
  },
  {
    id: 'club-ibarapa-poly-eruwa',
    name: 'RAC Ibarapa Polytechnic, Eruwa Campus',
    rotaryId: '213220',
    memberCount: 4,
    type: 'Campus',
    state: 'Oyo',
    city: 'Eruwa',
    region: 'South-West',
    meetingVenue: 'School of Science Lecture Hall, Eruwa',
    meetingSchedule: 'Every Friday · 4:00 PM',
    president: 'Kolade Adeyemi',
    coordinates: { lat: 7.5340, lng: 3.4210 },
  },
  {
    id: 'club-lautech-ogbomoso',
    name: 'RAC Lautech',
    rotaryId: '45480',
    memberCount: 10,
    type: 'Campus',
    state: 'Oyo',
    city: 'Ogbomoso',
    region: 'South-West',
    meetingVenue: 'MKO Hall, LAUTECH Campus, Ogbomoso',
    meetingSchedule: 'Every 2nd & 4th Saturday · 3:00 PM',
    president: 'Bamidele Olayiwola',
    coordinates: { lat: 8.1333, lng: 4.2567 },
  },
  {
    id: 'club-atiba-university',
    name: 'RAC Atiba University',
    rotaryId: '8825777',
    memberCount: 3,
    type: 'Campus',
    state: 'Oyo',
    city: 'Oyo Town',
    region: 'South-West',
    meetingVenue: 'Atiba University Senate Complex, Oyo',
    meetingSchedule: 'Every Wednesday · 4:00 PM',
    president: 'Ifeanyi Okonkwo',
    coordinates: { lat: 7.8210, lng: 3.9120 },
  },
  {
    id: 'club-eclub-ibadan-pacesetter',
    name: 'RAC E-Club of Ibadan Pacesetter',
    rotaryId: '8825776',
    memberCount: 21,
    type: 'E-Club',
    state: 'Oyo',
    city: 'Ibadan (Hybrid)',
    region: 'South-West',
    meetingVenue: 'Virtual (mostly Google Meet)',
    meetingSchedule: 'Every 2nd & 4th Sunday · 8:00 PM',
    president: 'Ifedolapo Iyanda',
    presidentAvatar: '/images/presidents/ifedolapo-iyanda.jpg',
    presidentPhone: '+234 903 852 0700',
    coordinates: { lat: 7.3775, lng: 3.9470 },
  },
  {
    id: 'club-adecom-college-egbeda',
    name: 'RAC Adecom College Egbeda',
    rotaryId: '8828912',
    memberCount: 14,
    type: 'Campus',
    state: 'Oyo',
    city: 'Egbeda, Ibadan',
    region: 'South-West',
    meetingVenue: 'Adecom College Campus, LR 4',
    meetingSchedule: 'Every Tuesday · 4:00 PM',
    president: 'Oyetola Micheal',
    presidentAvatar: '/images/presidents/oyetola-micheal.jpg',
    coordinates: { lat: 7.3850, lng: 3.9980 },
  },

  // SOUTH-WEST REGION — Osun State (16 Clubs)
  {
    id: 'club-osogbo',
    name: 'RAC Osogbo',
    rotaryId: '15923',
    memberCount: 16,
    type: 'Community',
    state: 'Osun',
    city: 'Osogbo',
    region: 'South-West',
    meetingVenue: 'Heritage Hotel Conference Hall, Gbongan Road, Osogbo',
    meetingSchedule: 'Every 1st & 3rd Sunday · 4:30 PM',
    president: 'Akinola Olufemi',
    coordinates: { lat: 7.7827, lng: 4.5418 },
  },
  {
    id: 'club-osogbo-central',
    name: 'RAC Osogbo Central',
    rotaryId: '215585',
    memberCount: 4,
    type: 'Community',
    state: 'Osun',
    city: 'Osogbo',
    region: 'South-West',
    meetingVenue: 'Ideal Nest Hotel Hall, Ring Road, Osogbo',
    meetingSchedule: 'Every 2nd & 4th Sunday · 4:00 PM',
    president: 'Morufat Adeleke',
    coordinates: { lat: 7.7710, lng: 4.5580 },
  },
  {
    id: 'club-uniosun-osogbo',
    name: 'RAC Osun State University Osogbo Campus',
    rotaryId: '89365',
    memberCount: 10,
    type: 'Campus',
    state: 'Osun',
    city: 'Osogbo',
    region: 'South-West',
    meetingVenue: 'Main Campus ETF Hall, UNIOSUN, Osogbo',
    meetingSchedule: 'Every Wednesday · 4:30 PM',
    president: 'Sulaimon Adeleke',
    coordinates: { lat: 7.7560, lng: 4.6020 },
  },
  {
    id: 'club-fountain-univ',
    name: 'RAC Fountain University, Osogbo',
    rotaryId: '8827590',
    memberCount: 9,
    type: 'Campus',
    state: 'Osun',
    city: 'Osogbo',
    region: 'South-West',
    meetingVenue: 'Auditorium Hall, Fountain University, Osogbo',
    meetingSchedule: 'Every Thursday · 4:00 PM',
    president: 'Zainab Lawal',
    coordinates: { lat: 7.7630, lng: 4.5820 },
  },
  {
    id: 'club-lautech-th-osogbo',
    name: 'RAC Lautech Teaching Hospital Osogbo',
    rotaryId: '218098',
    memberCount: 7,
    type: 'Campus',
    state: 'Osun',
    city: 'Osogbo',
    region: 'South-West',
    meetingVenue: 'College of Health Sciences Complex, LTH Osogbo',
    meetingSchedule: 'Every 2nd & 4th Saturday · 4:00 PM',
    president: 'Nurse Deborah Idowu',
    coordinates: { lat: 7.7890, lng: 4.5610 },
  },
  {
    id: 'club-oau-ile-ife-1',
    name: 'RAC OAU Ile-Ife',
    rotaryId: '8827783',
    memberCount: 9,
    type: 'Campus',
    state: 'Osun',
    city: 'Ile-Ife',
    region: 'South-West',
    meetingVenue: 'Amphitheatre Floor, OAU Campus, Ile-Ife',
    meetingSchedule: 'Every Friday · 5:00 PM',
    president: 'Kolawole Ogundimu',
    coordinates: { lat: 7.5186, lng: 4.5284 },
  },
  {
    id: 'club-ede-cb',
    name: 'RAC Ede Community Based',
    rotaryId: '90075',
    memberCount: 7,
    type: 'Community',
    state: 'Osun',
    city: 'Ede',
    region: 'South-West',
    meetingVenue: 'Ede Town Hall, Timi Market Square, Ede',
    meetingSchedule: 'Every 1st & 3rd Saturday · 4:00 PM',
    president: 'Taofeek Adigun',
    coordinates: { lat: 7.7380, lng: 4.4450 },
  },
  {
    id: 'club-fed-poly-ede',
    name: 'RAC Federal Polytechnic Ede',
    rotaryId: '43553',
    memberCount: 3,
    type: 'Campus',
    state: 'Osun',
    city: 'Ede',
    region: 'South-West',
    meetingVenue: 'South Campus Pavilion, Fed Poly Ede',
    meetingSchedule: 'Every Wednesday · 4:00 PM',
    president: 'Ayobami Ishola',
    coordinates: { lat: 7.7290, lng: 4.4310 },
  },
  {
    id: 'club-harvard-poly',
    name: 'RAC Harvard Polytechnic',
    rotaryId: '8826970',
    memberCount: 16,
    type: 'Campus',
    state: 'Osun',
    city: 'Ilesa Axis',
    region: 'South-West',
    meetingVenue: 'Harvard Poly Main Hall, Iloro, Ilesa Axis',
    meetingSchedule: 'Every Tuesday · 4:00 PM',
    president: 'Boluwatife Ojo',
    coordinates: { lat: 7.5310, lng: 4.5120 },
  },
  {
    id: 'club-ikirun',
    name: 'RAC Ikirun',
    rotaryId: '57320',
    memberCount: 6,
    type: 'Community',
    state: 'Osun',
    city: 'Ikirun',
    region: 'South-West',
    meetingVenue: 'Akinrun Palace Hall Extension, Ikirun',
    meetingSchedule: 'Every 2nd & 4th Sunday · 4:00 PM',
    president: 'Kazeem Adeleke',
    coordinates: { lat: 7.9120, lng: 4.6610 },
  },
  {
    id: 'club-iragbiji-cb',
    name: 'RAC Iragbiji CB',
    rotaryId: '90749',
    memberCount: 5,
    type: 'Community',
    state: 'Osun',
    city: 'Iragbiji',
    region: 'South-West',
    meetingVenue: 'Aragbiji Community Hall, Iragbiji',
    meetingSchedule: 'Every 2nd & 4th Sunday · 4:00 PM',
    president: 'Mojisola Lawal',
    coordinates: { lat: 7.9020, lng: 4.6910 },
  },
  {
    id: 'club-iwo-cb',
    name: 'RAC Iwo Community Based',
    rotaryId: '214931',
    memberCount: 4,
    type: 'Community',
    state: 'Osun',
    city: 'Iwo',
    region: 'South-West',
    meetingVenue: 'Oluwo Palace Square Hall, Iwo',
    meetingSchedule: 'Every 1st & 3rd Sunday · 4:00 PM',
    president: 'Mukaila Popoola',
    coordinates: { lat: 7.6290, lng: 4.1810 },
  },
  {
    id: 'club-modakeke',
    name: 'RAC Modakeke',
    rotaryId: '213160',
    memberCount: 9,
    type: 'Community',
    state: 'Osun',
    city: 'Modakeke',
    region: 'South-West',
    meetingVenue: 'Modakeke Civic Center, Itasan Road, Modakeke',
    meetingSchedule: 'Every 2nd & 4th Sunday · 4:00 PM',
    president: 'Akinwale Ogunleye',
    coordinates: { lat: 7.4890, lng: 4.5510 },
  },
  {
    id: 'club-oyan',
    name: 'RAC Oyan',
    rotaryId: '8826726',
    memberCount: 9,
    type: 'Community',
    state: 'Osun',
    city: 'Oyan',
    region: 'South-West',
    meetingVenue: 'Oloyan Town Hall, Oyan',
    meetingSchedule: 'Every 1st & 3rd Saturday · 4:00 PM',
    president: 'Eunice Oyeniran',
    coordinates: { lat: 7.9820, lng: 4.7710 },
  },
  {
    id: 'club-uniosun-ipetu-ilesa',
    name: 'RAC University of Osun State Ipetu-Ilesa',
    rotaryId: '215840',
    memberCount: 7,
    type: 'Campus',
    state: 'Osun',
    city: 'Ipetu-Ijesa',
    region: 'South-West',
    meetingVenue: 'College of Education Lecture Complex, Ipetu-Ijesa',
    meetingSchedule: 'Every Wednesday · 4:00 PM',
    president: 'Samuel Agboola',
    coordinates: { lat: 7.4720, lng: 4.8910 },
  },
  {
    id: 'club-mm-college-health',
    name: 'RAC Margaret Mosunmola College of Health Science',
    rotaryId: '8826982',
    memberCount: 21,
    type: 'Campus',
    state: 'Osun',
    city: 'Owo/Osogbo Axis',
    region: 'South-West',
    meetingVenue: 'College Auditorium, MMCHS Campus, Owo/Osogbo Axis',
    meetingSchedule: 'Every Thursday · 4:00 PM',
    president: 'Hauwa Abubakar',
    coordinates: { lat: 7.6210, lng: 4.5420 },
  },

  // SOUTH-WEST REGION — Ondo State (5 Clubs)
  {
    id: 'club-akure',
    name: 'RAC Akure',
    rotaryId: '16021',
    memberCount: 4,
    type: 'Community',
    state: 'Ondo',
    city: 'Akure',
    region: 'South-West',
    meetingVenue: 'Sunview Hotel Banquet Room, Alagbaka, Akure',
    meetingSchedule: 'Every 1st & 3rd Sunday · 4:00 PM',
    president: 'Bamidele Rotimi',
    coordinates: { lat: 7.2571, lng: 5.2058 },
  },
  {
    id: 'club-futa-akure',
    name: 'RAC Federal University of Technology Akure',
    rotaryId: '15991',
    memberCount: 22,
    type: 'Campus',
    state: 'Ondo',
    city: 'Akure',
    region: 'South-West',
    meetingVenue: 'SEET Auditorium, FUTA Campus, Akure',
    meetingSchedule: 'Every Wednesday · 5:00 PM',
    president: 'Victor Akinyemi',
    coordinates: { lat: 7.3034, lng: 5.1378 },
  },
  {
    id: 'club-aaua-akungba',
    name: 'RAC Adekunle Ajasin University',
    rotaryId: '62102',
    memberCount: 3,
    type: 'Campus',
    state: 'Ondo',
    city: 'Akungba-Akoko',
    region: 'South-West',
    meetingVenue: 'Faculty of Arts Theatre, AAUA Campus, Akungba-Akoko',
    meetingSchedule: 'Every Thursday · 4:30 PM',
    president: 'Gbenga Adegoke',
    coordinates: { lat: 7.4720, lng: 5.7510 },
  },
  {
    id: 'club-adeyemi-univ-ondo',
    name: 'RAC Adeyemi Federal University of Education, Ondo',
    rotaryId: '43033',
    memberCount: 5,
    type: 'Campus',
    state: 'Ondo',
    city: 'Ondo City',
    region: 'South-West',
    meetingVenue: 'Olusegun Obasanjo Auditorium, AFUED, Ondo City',
    meetingSchedule: 'Every Friday · 4:00 PM',
    president: 'Mercy Akinwumi',
    coordinates: { lat: 7.0910, lng: 4.8320 },
  },
  {
    id: 'club-ondo-city',
    name: 'RAC Ondo City',
    rotaryId: '8828614',
    memberCount: 22,
    type: 'Community',
    state: 'Ondo',
    city: 'Ondo City',
    region: 'South-West',
    meetingVenue: 'Ondo Civic Hall, Yaba Street, Ondo City',
    meetingSchedule: 'Every 2nd & 4th Sunday · 4:00 PM',
    president: 'Sunday Fasakin',
    coordinates: { lat: 7.0980, lng: 4.8410 },
  },

  // SOUTH-WEST REGION — Ekiti State (6 Clubs)
  {
    id: 'club-abuad-ado-ekiti',
    name: 'RAC ABUAD',
    rotaryId: '8827237',
    memberCount: 17,
    type: 'Campus',
    state: 'Ekiti',
    city: 'Ado-Ekiti',
    region: 'South-West',
    meetingVenue: 'Alfa Belgore Hall, Afe Babalola University, Ado-Ekiti',
    meetingSchedule: 'Every Friday · 5:00 PM',
    president: 'Damilare Falana',
    coordinates: { lat: 7.6010, lng: 5.3120 },
  },
  {
    id: 'club-eksu-ado-ekiti',
    name: 'RAC Ekiti State University',
    rotaryId: '81710',
    memberCount: 2,
    type: 'Campus',
    state: 'Ekiti',
    city: 'Ado-Ekiti',
    region: 'South-West',
    meetingVenue: 'Faculty of Science Lecture Theatre, EKSU, Ado-Ekiti',
    meetingSchedule: 'Every Wednesday · 4:00 PM',
    president: 'Olamide Awe',
    coordinates: { lat: 7.7126, lng: 5.2536 },
  },
  {
    id: 'club-fed-poly-ado',
    name: 'RAC Federal Polytechnic CEC Ado-Ekiti',
    rotaryId: '90629',
    memberCount: 4,
    type: 'Campus',
    state: 'Ekiti',
    city: 'Ado-Ekiti',
    region: 'South-West',
    meetingVenue: 'Continuing Education Centre Complex, Fed Poly Ado',
    meetingSchedule: 'Every Thursday · 4:00 PM',
    president: 'Rotimi Ogundele',
    coordinates: { lat: 7.6213, lng: 5.2215 },
  },
  {
    id: 'club-fuoye-ekiti',
    name: 'RAC Federal University, Oye-Ekiti',
    rotaryId: '8823786',
    memberCount: 10,
    type: 'Campus',
    state: 'Ekiti',
    city: 'Oye-Ekiti',
    region: 'South-West',
    meetingVenue: 'Faculty of Engineering Hall, FUOYE Campus, Ikole/Oye',
    meetingSchedule: 'Every Thursday · 4:30 PM',
    president: 'Emmanuel Ayodele',
    coordinates: { lat: 7.7980, lng: 5.3310 },
  },
  {
    id: 'club-espahms-ijero',
    name: 'RAC ESPAHMS Ijero',
    rotaryId: '8827236',
    memberCount: 11,
    type: 'Campus',
    state: 'Ekiti',
    city: 'Ijero-Ekiti',
    region: 'South-West',
    meetingVenue: 'College Main Auditorium, ESPAHMS, Ijero-Ekiti',
    meetingSchedule: 'Every Tuesday · 4:00 PM',
    president: 'Tolulope Ogunleye',
    coordinates: { lat: 7.8120, lng: 5.0610 },
  },
  {
    id: 'club-school-health-tech',
    name: 'RAC School of Health Technology',
    rotaryId: '86285',
    memberCount: 7,
    type: 'Campus',
    state: 'Ekiti',
    city: 'Ijero-Ekiti',
    region: 'South-West',
    meetingVenue: 'Health Science Lecture Theatre, Ijero-Ekiti',
    meetingSchedule: 'Every Wednesday · 4:00 PM',
    president: 'Bunmi Aladesanmi',
    coordinates: { lat: 7.8210, lng: 5.0720 },
  },

  // NORTH-CENTRAL REGION — Kwara State (10 Clubs)
  {
    id: 'club-ilorin',
    name: 'RAC Ilorin',
    rotaryId: '15961',
    memberCount: 9,
    type: 'Community',
    state: 'Kwara',
    city: 'Ilorin',
    region: 'North-Central',
    meetingVenue: 'Kwara Hotels Conference Suite, GRA, Ilorin',
    meetingSchedule: 'Every 1st & 3rd Sunday · 4:00 PM',
    president: 'Mustapha Sanni',
    coordinates: { lat: 8.4799, lng: 4.5418 },
  },
  {
    id: 'club-ilorin-metro',
    name: 'RAC Ilorin Metro',
    rotaryId: '212439',
    memberCount: 8,
    type: 'Community',
    state: 'Kwara',
    city: 'Ilorin',
    region: 'North-Central',
    meetingVenue: 'Metropolitan Hotel Hall, Unity Road, Ilorin',
    meetingSchedule: 'Every 2nd & 4th Sunday · 4:00 PM',
    president: 'Rilwan Ahmed',
    coordinates: { lat: 8.4910, lng: 4.5620 },
  },
  {
    id: 'club-ilorin-gra',
    name: 'RAC Ilorin GRA',
    rotaryId: '214785',
    memberCount: 13,
    type: 'Community',
    state: 'Kwara',
    city: 'Ilorin',
    region: 'North-Central',
    meetingVenue: 'Princess Luxury Hotel Banquet Room, GRA, Ilorin',
    meetingSchedule: 'Every 1st & 3rd Saturday · 4:30 PM',
    president: 'Abdulrahman Yusuf',
    coordinates: { lat: 8.4680, lng: 4.5510 },
  },
  {
    id: 'club-ilorin-golden',
    name: 'RAC Ilorin Golden',
    rotaryId: '8823814',
    memberCount: 1,
    type: 'Community',
    state: 'Kwara',
    city: 'Ilorin',
    region: 'North-Central',
    meetingVenue: 'Golden Tulip Hall, Ilorin',
    meetingSchedule: 'Every 2nd & 4th Sunday · 4:00 PM',
    president: 'Fatima Abdullahi',
    coordinates: { lat: 8.5020, lng: 4.5310 },
  },
  {
    id: 'club-ilorin-new-dawn',
    name: 'RAC Ilorin New Dawn',
    rotaryId: '216894',
    memberCount: 2,
    type: 'Community',
    state: 'Kwara',
    city: 'Ilorin',
    region: 'North-Central',
    meetingVenue: 'De Peace Hotel Conference Suite, Ilorin',
    meetingSchedule: 'Every 1st & 3rd Sunday · 4:00 PM',
    president: 'Zainab Ibrahim',
    coordinates: { lat: 8.4810, lng: 4.5720 },
  },
  {
    id: 'club-ilorin-fate-neighbourhood',
    name: 'RAC Ilorin Fate Neighbourhood Community Base',
    rotaryId: '216995',
    memberCount: 5,
    type: 'Community',
    state: 'Kwara',
    city: 'Ilorin',
    region: 'North-Central',
    meetingVenue: 'Fate Community Hall, Fate Road, Ilorin',
    meetingSchedule: 'Every 2nd & 4th Saturday · 4:00 PM',
    president: 'Habeeb Solagberu',
    coordinates: { lat: 8.4980, lng: 4.5820 },
  },
  {
    id: 'club-unilorin-campus',
    name: 'RAC University of Ilorin',
    rotaryId: '15899',
    memberCount: 7,
    type: 'Campus',
    state: 'Kwara',
    city: 'Ilorin',
    region: 'North-Central',
    meetingVenue: 'Student Union Building, Main Campus, UNILORIN',
    meetingSchedule: 'Every Thursday · 4:30 PM',
    president: 'Aliyu Olanrewaju',
    coordinates: { lat: 8.4842, lng: 4.6728 },
  },
  {
    id: 'club-nursing-ilorin',
    name: 'RAC College of Nursing and Midwifery, Ilorin',
    rotaryId: '8825220',
    memberCount: 8,
    type: 'Campus',
    state: 'Kwara',
    city: 'Ilorin',
    region: 'North-Central',
    meetingVenue: 'College Lecture Auditorium, Post Office Area, Ilorin',
    meetingSchedule: 'Every Wednesday · 4:00 PM',
    president: 'Amina Gambari',
    coordinates: { lat: 8.4710, lng: 4.5380 },
  },
  {
    id: 'club-nursing-uith',
    name: 'RAC College of Nursing Sciences (UITH)',
    rotaryId: '8828433',
    memberCount: 15,
    type: 'Campus',
    state: 'Kwara',
    city: 'Ilorin',
    region: 'North-Central',
    meetingVenue: 'UITH Complex Lecture Hall, Oke Oyi, Ilorin',
    meetingSchedule: 'Every Thursday · 4:30 PM',
    president: 'Nurudeen Kolawole',
    coordinates: { lat: 8.5280, lng: 4.5910 },
  },
  {
    id: 'club-offa-metro',
    name: 'RAC Offa Metropolitan',
    rotaryId: '8823807',
    memberCount: 5,
    type: 'Community',
    state: 'Kwara',
    city: 'Offa',
    region: 'North-Central',
    meetingVenue: 'Offa Civic Hall, Olofa Way, Offa',
    meetingSchedule: 'Every 1st & 3rd Sunday · 4:00 PM',
    president: 'Olawale Popoola',
    coordinates: { lat: 8.1490, lng: 4.7180 },
  },

  // NORTH-CENTRAL REGION — Niger State (4 Clubs)
  {
    id: 'club-minna-central',
    name: 'RAC Minna Central',
    rotaryId: '8829101',
    memberCount: 12,
    type: 'Community',
    state: 'Niger',
    city: 'Minna',
    region: 'North-Central',
    meetingVenue: 'Hydro Hotel Conference Hall, Minna',
    meetingSchedule: 'Every 2nd & 4th Saturday · 4:00 PM',
    president: 'Ibrahim Mohammed',
    coordinates: { lat: 9.6178, lng: 6.5569 },
  },
  {
    id: 'club-futminna-bosso',
    name: 'RAC FUTMinna',
    rotaryId: '8829102',
    memberCount: 18,
    type: 'Campus',
    state: 'Niger',
    city: 'Minna',
    region: 'North-Central',
    meetingVenue: 'Bosso Campus Auditorium, FUT Minna',
    meetingSchedule: 'Every Wednesday · 4:00 PM',
    president: 'Usman Bello',
    coordinates: { lat: 9.5833, lng: 6.5500 },
  },
  {
    id: 'club-bida-central',
    name: 'RAC Bida Central',
    rotaryId: '8829103',
    memberCount: 8,
    type: 'Community',
    state: 'Niger',
    city: 'Bida',
    region: 'North-Central',
    meetingVenue: 'Bida Town Hall, Poly Road, Bida',
    meetingSchedule: 'Every 1st & 3rd Sunday · 4:00 PM',
    president: 'Fatima Umar',
    coordinates: { lat: 9.0833, lng: 6.0167 },
  },
  {
    id: 'club-suleja-metro',
    name: 'RAC Suleja Metro',
    rotaryId: '8829104',
    memberCount: 14,
    type: 'Community',
    state: 'Niger',
    city: 'Suleja',
    region: 'North-Central',
    meetingVenue: 'Royal Tropicana Hotel Conference Hall, Suleja',
    meetingSchedule: 'Every 2nd & 4th Sunday · 4:30 PM',
    president: 'Mustapha Aliyu',
    coordinates: { lat: 9.1800, lng: 7.1800 },
  },

  // NORTH-CENTRAL REGION — Kogi State (9 Clubs)
  {
    id: 'club-lokoja-cb',
    name: 'RAC Lokoja CB',
    rotaryId: '8823883',
    memberCount: 5,
    type: 'Community',
    state: 'Kogi',
    city: 'Lokoja',
    region: 'North-Central',
    meetingVenue: 'Confluence Beach Hotel Banquet Room, Lokoja',
    meetingSchedule: 'Every 1st & 3rd Sunday · 4:00 PM',
    president: 'Gabriel Attah',
    coordinates: { lat: 7.7969, lng: 6.7405 },
  },
  {
    id: 'club-ful-lokoja',
    name: 'RAC Federal University Lokoja',
    rotaryId: '91235',
    memberCount: 4,
    type: 'Campus',
    state: 'Kogi',
    city: 'Lokoja',
    region: 'North-Central',
    meetingVenue: 'Adankolo Campus Auditorium, FULokoja',
    meetingSchedule: 'Every Thursday · 4:30 PM',
    president: 'Samuel Audu',
    coordinates: { lat: 7.8120, lng: 6.7210 },
  },
  {
    id: 'club-kogi-poly-lokoja',
    name: 'RAC Kogi State Polytechnic Lokoja',
    rotaryId: '88486',
    memberCount: 3,
    type: 'Campus',
    state: 'Kogi',
    city: 'Lokoja',
    region: 'North-Central',
    meetingVenue: 'Main Campus Assembly Complex, Lokoja',
    meetingSchedule: 'Every Wednesday · 4:00 PM',
    president: 'Hassan Danjuma',
    coordinates: { lat: 7.8010, lng: 6.7320 },
  },
  {
    id: 'club-ankpa-central',
    name: 'RAC Ankpa Central',
    rotaryId: '91440',
    memberCount: 2,
    type: 'Community',
    state: 'Kogi',
    city: 'Ankpa',
    region: 'North-Central',
    meetingVenue: 'Ankpa Civic Hall, Main Road, Ankpa',
    meetingSchedule: 'Every 1st & 3rd Saturday · 4:00 PM',
    president: 'Aliyu Usman',
    coordinates: { lat: 7.3710, lng: 7.6320 },
  },
  {
    id: 'club-ankpa-cb',
    name: 'RAC Ankpa Community Base',
    rotaryId: '91447',
    memberCount: 1,
    type: 'Community',
    state: 'Kogi',
    city: 'Ankpa',
    region: 'North-Central',
    meetingVenue: 'Community Hall, Ankpa Town',
    meetingSchedule: 'Every 2nd & 4th Sunday · 4:00 PM',
    president: 'Musa Yakubu',
    coordinates: { lat: 7.3620, lng: 7.6410 },
  },
  {
    id: 'club-alhikma-ankpa',
    name: 'RAC Alhikma C.O.E. Ankpa',
    rotaryId: '91446',
    memberCount: 3,
    type: 'Campus',
    state: 'Kogi',
    city: 'Ankpa',
    region: 'North-Central',
    meetingVenue: 'Alhikma College of Education Auditorium, Ankpa',
    meetingSchedule: 'Every Tuesday · 4:00 PM',
    president: 'Zubairu Abubakar',
    coordinates: { lat: 7.3810, lng: 7.6210 },
  },
  {
    id: 'club-idah-cb',
    name: 'RAC Idah Community Base',
    rotaryId: '88728',
    memberCount: 7,
    type: 'Community',
    state: 'Kogi',
    city: 'Idah',
    region: 'North-Central',
    meetingVenue: 'Attah Igala Palace Hall Axis, Idah',
    meetingSchedule: 'Every 1st & 3rd Sunday · 4:00 PM',
    president: 'Idris Ocholi',
    coordinates: { lat: 7.1120, lng: 6.7410 },
  },
  {
    id: 'club-dekina-cb',
    name: 'RAC Dekina Community Base',
    rotaryId: '91436',
    memberCount: 5,
    type: 'Community',
    state: 'Kogi',
    city: 'Dekina',
    region: 'North-Central',
    meetingVenue: 'Dekina Town Assembly Hall, Dekina',
    meetingSchedule: 'Every 2nd & 4th Saturday · 4:00 PM',
    president: 'Eneojo Ameh',
    coordinates: { lat: 7.6910, lng: 7.0420 },
  },
  {
    id: 'club-ugwolawo-cb',
    name: 'RAC Ugwolawo C.B.',
    rotaryId: '88654',
    memberCount: 2,
    type: 'Community',
    state: 'Kogi',
    city: 'Ugwolawo',
    region: 'North-Central',
    meetingVenue: 'Ugwolawo Community Square, Ofu LGA',
    meetingSchedule: 'Every 1st & 3rd Sunday · 4:00 PM',
    president: 'Ochimana David',
    coordinates: { lat: 7.2410, lng: 6.9210 },
  },

  // E-CLUBS & CROSS-REGIONAL (7 Clubs)
  {
    id: 'club-eclub-mighty',
    name: 'RAC E-Club Mighty',
    rotaryId: '8825437',
    memberCount: 11,
    type: 'E-Club',
    state: 'E-Clubs',
    city: 'Online / Virtual',
    region: 'North-Central',
    meetingVenue: 'Virtual Sessions (Zoom / Google Meet)',
    meetingSchedule: 'Every 1st & 3rd Sunday · 8:00 PM',
    president: 'Chinedu Eze',
    coordinates: { lat: 8.4799, lng: 4.5418 },
  },
  {
    id: 'club-eclub-greater-nigeria',
    name: 'RAC E-Club of Greater Nigeria',
    rotaryId: '214084',
    memberCount: 16,
    type: 'E-Club',
    state: 'E-Clubs',
    city: 'Online / Virtual',
    region: 'South-West',
    meetingVenue: 'Virtual Headquarters / Google Meet',
    meetingSchedule: 'Every 2nd & 4th Sunday · 7:00 PM',
    president: 'Olawale Adeniyi',
    coordinates: { lat: 7.3775, lng: 3.9470 },
  },
  {
    id: 'club-eclub-greater-ng-golden',
    name: 'RAC E-Club of Greater Nigeria Golden',
    rotaryId: '218582',
    memberCount: 10,
    type: 'E-Club',
    state: 'E-Clubs',
    city: 'Online / Virtual',
    region: 'South-West',
    meetingVenue: 'Virtual Platform (Zoom Link Broadcast)',
    meetingSchedule: 'Every 1st & 3rd Saturday · 7:30 PM',
    president: 'Funmilayo Adeyemi',
    coordinates: { lat: 7.4443, lng: 3.8997 },
  },
  {
    id: 'club-eclub-harmony',
    name: 'RAC E-Club of Harmony',
    rotaryId: '8826253',
    memberCount: 19,
    type: 'E-Club',
    state: 'E-Clubs',
    city: 'Online / Virtual',
    region: 'North-Central',
    meetingVenue: 'Online Assembly (Zoom & Discord)',
    meetingSchedule: 'Every 2nd & 4th Thursday · 8:00 PM',
    president: 'Ifeoma Okafor',
    coordinates: { lat: 8.4842, lng: 4.6728 },
  },
  {
    id: 'club-eclub-ng-new-dawn',
    name: 'RAC E-Club of Nigeria New Dawn',
    rotaryId: '8827195',
    memberCount: 14,
    type: 'E-Club',
    state: 'E-Clubs',
    city: 'Online / Virtual',
    region: 'South-West',
    meetingVenue: 'Virtual Sessions (Google Meet Hub)',
    meetingSchedule: 'Every 1st & 3rd Wednesday · 7:30 PM',
    president: 'Babatunde Soyinka',
    coordinates: { lat: 7.7827, lng: 4.5418 },
  },
  {
    id: 'club-eclub-one-nigeria',
    name: 'RAC E-Club of One Nigeria',
    rotaryId: '8826376',
    memberCount: 11,
    type: 'E-Club',
    state: 'E-Clubs',
    city: 'Online / Virtual',
    region: 'North-Central',
    meetingVenue: 'Online Rotaract Lounge / Zoom',
    meetingSchedule: 'Every 2nd & 4th Sunday · 8:00 PM',
    president: 'Tariro Moyo',
    coordinates: { lat: 7.7969, lng: 6.7405 },
  },
  {
    id: 'club-eclub-peace-nigeria',
    name: 'RAC E-Club of Peace Nigeria',
    rotaryId: '8828549',
    memberCount: 10,
    type: 'E-Club',
    state: 'E-Clubs',
    city: 'Online / Virtual',
    region: 'South-West',
    meetingVenue: 'Online Peace Hub / Zoom',
    meetingSchedule: 'Every 1st & 3rd Friday · 8:00 PM',
    president: 'Zainab Danjuma',
    coordinates: { lat: 7.2571, lng: 5.2058 },
  },
];
