/**
 * Tier 1 - Suite 06: Projects Service (`projects-service.ts`) Test Suite
 */

import {
  expectEqual,
  expectTruthy,
  expectDefined,
  expectSchemaValid,
} from '../helpers/assertions';
import {
  getStoredProjects,
  saveProject,
  updateProject,
  deleteProject,
  subscribeToProjects,
  INITIAL_PROJECTS,
  ProjectItem,
} from '../../lib/services/projects-service';

export async function run(): Promise<{
  name: string;
  passed: number;
  failed: number;
  tests: { name: string; status: 'pass' | 'fail'; error?: string }[];
}> {
  const suiteName = 'Tier 1 - 06: Projects Service (Real-Time CRUD & Live Subscriptions)';
  const tests: { name: string; status: 'pass' | 'fail'; error?: string }[] = [];
  let passed = 0;
  let failed = 0;

  async function executeTest(name: string, fn: () => Promise<void> | void) {
    try {
      await fn();
      tests.push({ name, status: 'pass' });
      passed++;
    } catch (err: any) {
      tests.push({ name, status: 'fail', error: err?.message || String(err) });
      failed++;
    }
  }

  // 1. Initial Projects Retrieval
  await executeTest('getStoredProjects(): Retrieves baseline list of community projects', () => {
    const projects = getStoredProjects();
    expectTruthy(Array.isArray(projects), 'Should return an array of projects');
    expectTruthy(projects.length >= 4, 'Should contain at least 4 initial projects');
    expectEqual(projects[0].id, INITIAL_PROJECTS[0].id);
  });

  // 2. Project Creation (saveProject)
  let createdProjectId: string;
  await executeTest('saveProject(): Creates a new project with autogenerated ID and timestamp', () => {
    const newProjectInput: Omit<ProjectItem, 'id' | 'createdAt'> = {
      title: 'E-Library for Osun High Schools',
      category: 'Education',
      year: '2026',
      club: 'Rotaract Club of Osogbo Metro',
      location: 'Osogbo, Osun State',
      image: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=900&h=700&fit=crop',
      description: 'Equipping 5 public secondary schools with high-speed internet and digital learning materials.',
      status: 'In Progress',
      progress: 55,
      statNumber: '5',
      statLabel: 'Schools Equipped',
      stats: [
        { icon: 'book', value: '5', label: 'Schools' },
        { icon: 'users', value: '3,000', label: 'Students Reached' },
      ],
    };

    const saved = saveProject(newProjectInput);
    expectDefined(saved.id);
    expectTruthy(saved.id.startsWith('proj-'));
    expectEqual(saved.title, 'E-Library for Osun High Schools');
    expectEqual(saved.progress, 55);
    expectDefined(saved.createdAt);
    createdProjectId = saved.id;
  });

  // 3. Project Update (updateProject)
  await executeTest('updateProject(): Mutates project progress and fields seamlessly', () => {
    const updated = updateProject(createdProjectId, {
      progress: 100,
      status: 'Completed',
      description: 'Project fully completed and handed over to school principals.',
    });

    expectDefined(updated);
    expectEqual(updated.progress, 100);
    expectEqual(updated.status, 'Completed');
    expectEqual(updated.description, 'Project fully completed and handed over to school principals.');
  });

  // 4. Project Deletion (deleteProject)
  await executeTest('deleteProject(): Removes project by ID and verifies collection state', () => {
    const deleted = deleteProject(createdProjectId);
    expectEqual(deleted, true);

    const projects = getStoredProjects();
    const stillExists = projects.some((p) => p.id === createdProjectId);
    expectEqual(stillExists, false);
  });

  // 5. Subscription Mechanism (subscribeToProjects)
  await executeTest('subscribeToProjects(): Registers callback listener and returns unsubscribe cleanup function', () => {
    let triggered = false;
    const unsubscribe = subscribeToProjects((projects) => {
      triggered = true;
      expectTruthy(Array.isArray(projects));
    });

    expectTruthy(typeof unsubscribe === 'function', 'Subscription must return an unsubscribe function');
    unsubscribe();
  });

  return {
    name: suiteName,
    passed,
    failed,
    tests,
  };
}
